name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        otp:
          - '23.3'
        elixir:
          - '1.11'
        include:
          - elixir: '1.11'
            otp: '22.3'
          - elixir: '1.10'
            otp: '21.3'
          - elixir: '1.9.4'
            otp: '21.3'
          - elixir: '1.8.2'
            otp: '20.3'
          - elixir: '1.7'
            otp: '19.3'
          - elixir: '1.6'
            otp: '19.3'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Setup Environment
      run: |
        epmd -daemon
        mix local.hex --force
        mix local.rebar --force

    - name: Install dependencies
      run: |
        mix deps.get
        MIX_ENV=test mix deps.compile

    - name: Run tests
      run: mix test --trace
